### ISSUE TITLE
REPO README

### ISSUE THREAD

**Issue by Peeuser121** [darikarmy/octo-solidcolors#1]
WARNING! THIS CONTAINS COLORS THAT MAY HURT YOUR EYES.

Welcome! This is octo-solidcolors! It have 20 solid colors for your malwares. You can download them if you want to. If you can't see white. That means your currently on the light theme. To see white. switch from light to dark!

[Repo by me]

**Comment by Peeuser121** [comment]
Solidcolor 1-10. By UwU-master 




[What does this solidcolor creator put in h-the name???]

**Comment by Peeuser121** [comment]
Solidcolor 11-15. By Nestor1/NestorUSED21


[Thats me! The Owner!]

**Comment by ghost** [comment]
e

**Comment by Peeuser121** [comment]
b word
