### ISSUE TITLE
By UwU-master

### ISSUE THREAD

**Issue by Peeuser121** [darikarmy/octo-solidcolors#2]
By UwU-master
-----------------------------------------------------------------
Solidcolor1
Solidcolor2
Solidcolor1DOT5 [in octosolidcolors2]
Solidcolor2DOT5 [in octosolidcolors2]
Solidcolor3
Solidcolor4
Solidcolor5
Solidcolor6
Solidcolor6DOT5 [in octosolidcolors2]
Solidcolor7
Solidcolor8
Solidcolor9
Solidcolor10
Solidcolor10DOT5 [in octosolidcolors2]

**Comment by ghost** [comment]
...

**Comment by Peeuser121** [comment]
More Coming soon!
